ruby:
  enabled: false

coffeescript:
  enabled: false

jshint:
  config_file: .jshintrc

jshint:
  ignore_file: .jshintignore

scss:
  enabled: false

haml:
  enabled: false

go:
  enabled: false

swift:
  enabled: false

eslint:
  enabled: true

eslint:
  config_file: .eslintrc.js

eslint:
  ignore_file: .eslintignore
